# Generated by Django 5.0.2 on 2024-02-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefield',
            name='field',
            field=models.JSONField(null=True, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='gamefield',
            name='field_bomb',
            field=models.JSONField(null=True, verbose_name='bomb field'),
        ),
    ]
