# Generated by Django 5.0.2 on 2024-02-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_game_created_at_game_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamefield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
